kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      repo: azlux/borgbackup
      platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest

node:
  location: local

trigger:
  event:
    - push

---
kind: pipeline
type: docker
name: cron

steps:
  - name: docker
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      repo: azlux/borgbackup
      platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest

node:
  location: local

trigger:
  event:
    - cron
  cron:
    - os-update
