kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: azlux/borgbackup
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest

trigger:
  event:
    - push

---
kind: pipeline
type: docker
name: cron

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: azlux/borgbackup
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest

trigger:
  event:
    - cron
  cron:
    - os-update
